services:
  - type: web
    name: acad-app
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acad-app-db
          property: connectionString

databases:
  - name: acad-app-db
    plan: free
